/*
 * Se for usar este código, cite o autor.
 */
package controleobi2.visao;

import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Alexandre Romanelli <alexandre.romanelli@ifes.edu.br>
 */
public class JFramePrincipal extends javax.swing.JFrame {

    /**
     * Creates new form JFramePrincipal
     */
    public JFramePrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonCadastroModalidade = new javax.swing.JButton();
        jButtonCadastroNivelModalidade = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Controle OBI");

        jButtonCadastroModalidade.setText("Cadastro de modalidade");
        jButtonCadastroModalidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCadastroModalidadeActionPerformed(evt);
            }
        });

        jButtonCadastroNivelModalidade.setText("Cadastro de nível de modalidade");
        jButtonCadastroNivelModalidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCadastroNivelModalidadeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButtonCadastroNivelModalidade, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonCadastroModalidade, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(579, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jButtonCadastroModalidade)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonCadastroNivelModalidade)
                .addContainerGap(393, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCadastroModalidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadastroModalidadeActionPerformed
        JPanelRegistroModalidade jPanelRegistroModalidade = 
                new JPanelRegistroModalidade();
        JFrame frame = new JFrame();
        frame.add(jPanelRegistroModalidade);
        frame.pack();
        frame.setTitle("Registro de modalidade");
        frame.setVisible(true);
    }//GEN-LAST:event_jButtonCadastroModalidadeActionPerformed

    private void jButtonCadastroNivelModalidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadastroNivelModalidadeActionPerformed
        JOptionPane.showMessageDialog(null, 
                "Você clicou no botão \"Cadastro de nível de modalidade\".", 
                "Utilidade pública", 
                JOptionPane.PLAIN_MESSAGE);
    }//GEN-LAST:event_jButtonCadastroNivelModalidadeActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCadastroModalidade;
    private javax.swing.JButton jButtonCadastroNivelModalidade;
    // End of variables declaration//GEN-END:variables
}
