/*
 * Se for usar este código, cite o autor.
 */
package controleobi2.visao;

import controleobi2.modelo.dao.ModalidadeDAO;
import controleobi2.modelo.entidade.Modalidade;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author Alexandre Romanelli <alexandre.romanelli@ifes.edu.br>
 */
public class JPanelRegistroModalidade extends javax.swing.JPanel {
    
    enum Estado {
        Navegando,
        Editando
    }
    
    private ArrayList<Modalidade> listaModalidade;
    private Modalidade cursor;
    private ModalidadeDAO modalidadeDAO;
    
    private void ajustarExibicaoEstado(Estado estadoAtual) {
        switch (estadoAtual) {
            case Navegando:
                jTextFieldCodigo.setEditable(false);
                jTextFieldNome.setEditable(false);
                jTextFieldDescricao.setEditable(false);
                jButtonCancelar.setEnabled(false);
                jButtonSalvar.setEnabled(false);

                jButtonNovo.setEnabled(true);
                boolean haMaisDeUmRegistro = listaModalidade.size() > 1;
                jButtonPrimeiro.setEnabled(haMaisDeUmRegistro);
                jButtonAnterior.setEnabled(haMaisDeUmRegistro);
                jButtonProximo.setEnabled(haMaisDeUmRegistro);
                jButtonUltimo.setEnabled(haMaisDeUmRegistro);
                boolean haPeloMenosUmRegistro = listaModalidade.size() > 0;
                jButtonEditar.setEnabled(haPeloMenosUmRegistro);
                jButtonExcluir.setEnabled(haPeloMenosUmRegistro);
                break;

            case Editando:
                jTextFieldCodigo.setEditable(false);
                jTextFieldNome.setEditable(true);
                jTextFieldDescricao.setEditable(true);
                jButtonCancelar.setEnabled(true);
                jButtonSalvar.setEnabled(true);

                jButtonNovo.setEnabled(false);
                jButtonPrimeiro.setEnabled(false);
                jButtonAnterior.setEnabled(false);
                jButtonProximo.setEnabled(false);
                jButtonUltimo.setEnabled(false);
                jButtonEditar.setEnabled(false);
                jButtonExcluir.setEnabled(false);
                break;
        }
    }
    
    private void iniciarCursor() {
        cursor = null;
        if (listaModalidade.size() > 0) {
            cursor = listaModalidade.get(0);
        }
    }
    
    private void moverCursorProximo() {
        int pos = listaModalidade.indexOf(cursor);
        if (pos < listaModalidade.size() - 1) { // verifica se não é o último
            cursor = listaModalidade.get(pos + 1);
            exibirDadosCursor();
        }
    }
    
    private void moverCursorAnterior() {
        int pos = listaModalidade.indexOf(cursor);
        if (pos > 0) { // verifica se não é o primeiro
            cursor = listaModalidade.get(pos - 1);
            exibirDadosCursor();
        }
    }
    
    private void moverCursorPrimeiro() {
        if (listaModalidade.size() > 0) {
            cursor = listaModalidade.get(0);
            exibirDadosCursor();
        }
    }
    
    private void moverCursorUltimo() {
        if (listaModalidade.size() > 0) {
            cursor = listaModalidade.get(listaModalidade.size() - 1);
            exibirDadosCursor();
        }
    }
    
    private void exibirDadosCursor() {
        if (cursor != null) {
            jTextFieldCodigo.setText(Long.toString(cursor.getCodigo()));
            jTextFieldNome.setText(cursor.getNome());
            jTextFieldDescricao.setText(cursor.getDescricao());
        } else {
            jTextFieldCodigo.setText("");
            jTextFieldNome.setText("");
            jTextFieldDescricao.setText("");
        }
    }

    /**
     * Creates new form JPanelRegistroModalidade
     * @param modalidadeDAO
     */
    public JPanelRegistroModalidade(ModalidadeDAO modalidadeDAO) {
        initComponents();
        
        this.modalidadeDAO = modalidadeDAO;
        listaModalidade = modalidadeDAO.getLista();
        
        iniciarCursor();
        exibirDadosCursor();
        
        ajustarExibicaoEstado(Estado.Navegando);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldCodigo = new javax.swing.JTextField();
        jTextFieldNome = new javax.swing.JTextField();
        jTextFieldDescricao = new javax.swing.JTextField();
        jButtonPrimeiro = new javax.swing.JButton();
        jButtonAnterior = new javax.swing.JButton();
        jButtonProximo = new javax.swing.JButton();
        jButtonUltimo = new javax.swing.JButton();
        jButtonNovo = new javax.swing.JButton();
        jButtonExcluir = new javax.swing.JButton();
        jButtonSalvar = new javax.swing.JButton();
        jButtonEditar = new javax.swing.JButton();
        jButtonCancelar = new javax.swing.JButton();

        jLabel1.setText("Código");

        jLabel2.setText("Nome");

        jLabel3.setText("Descrição");

        jTextFieldNome.setToolTipText("Digite o nome da modalidade");

        jButtonPrimeiro.setText("Primeiro");
        jButtonPrimeiro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPrimeiroActionPerformed(evt);
            }
        });

        jButtonAnterior.setText("Anterior");
        jButtonAnterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAnteriorActionPerformed(evt);
            }
        });

        jButtonProximo.setText("Próximo");
        jButtonProximo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonProximoActionPerformed(evt);
            }
        });

        jButtonUltimo.setText("Último");
        jButtonUltimo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUltimoActionPerformed(evt);
            }
        });

        jButtonNovo.setText("Novo");
        jButtonNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNovoActionPerformed(evt);
            }
        });

        jButtonExcluir.setText("Excluir");
        jButtonExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExcluirActionPerformed(evt);
            }
        });

        jButtonSalvar.setText("Salvar");
        jButtonSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalvarActionPerformed(evt);
            }
        });

        jButtonEditar.setText("Editar");
        jButtonEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditarActionPerformed(evt);
            }
        });

        jButtonCancelar.setText("Cancelar");
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonPrimeiro)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonAnterior, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonProximo, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonUltimo, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButtonNovo, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonExcluir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 339, Short.MAX_VALUE)
                        .addComponent(jButtonCancelar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldDescricao)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFieldNome, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonPrimeiro)
                    .addComponent(jButtonAnterior)
                    .addComponent(jButtonProximo)
                    .addComponent(jButtonUltimo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextFieldCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextFieldNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextFieldDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonNovo)
                    .addComponent(jButtonExcluir)
                    .addComponent(jButtonEditar)
                    .addComponent(jButtonSalvar)
                    .addComponent(jButtonCancelar))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    protected void prepararParaNovoRegistro() {
        jTextFieldCodigo.setText("");
        jTextFieldNome.setText("");
        jTextFieldDescricao.setText("");
        ajustarExibicaoEstado(Estado.Editando);
        jTextFieldNome.requestFocus();
    }
    
    protected void prepararParaAlterarRegistro(Modalidade registro) {
        for (Modalidade m : listaModalidade) {
            if (m.getCodigo() == registro.getCodigo()) {
                cursor = m;
                break;
            }
        }
        exibirDadosCursor();
        ajustarExibicaoEstado(Estado.Editando);
        jTextFieldNome.requestFocus();
    }
    
    private void jButtonNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNovoActionPerformed
        prepararParaNovoRegistro();
    }//GEN-LAST:event_jButtonNovoActionPerformed

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
        if (JOptionPane.showConfirmDialog(null, "Confirmar cancelamento de edição?",
                "Cancelamento", JOptionPane.YES_NO_OPTION)
                == JOptionPane.YES_OPTION) {
            exibirDadosCursor();
            ajustarExibicaoEstado(Estado.Navegando);
        }
    }//GEN-LAST:event_jButtonCancelarActionPerformed

    private void jButtonPrimeiroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPrimeiroActionPerformed
        moverCursorPrimeiro();
    }//GEN-LAST:event_jButtonPrimeiroActionPerformed

    private void jButtonAnteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAnteriorActionPerformed
        moverCursorAnterior();
    }//GEN-LAST:event_jButtonAnteriorActionPerformed

    private void jButtonProximoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonProximoActionPerformed
        moverCursorProximo();
    }//GEN-LAST:event_jButtonProximoActionPerformed

    private void jButtonUltimoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUltimoActionPerformed
        moverCursorUltimo();
    }//GEN-LAST:event_jButtonUltimoActionPerformed

    private void jButtonEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditarActionPerformed
        ajustarExibicaoEstado(Estado.Editando);
        jTextFieldNome.requestFocus();
    }//GEN-LAST:event_jButtonEditarActionPerformed

    private void jButtonSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalvarActionPerformed
        if (jTextFieldCodigo.getText().isEmpty()) {
            // novo registro
            String nome = jTextFieldNome.getText();
            String descricao = jTextFieldDescricao.getText();
            Modalidade novaModalidade = new Modalidade(-1, nome, descricao);
            modalidadeDAO.inserir(novaModalidade);
            listaModalidade = modalidadeDAO.getLista();
            moverCursorUltimo();
            exibirDadosCursor();
        } else {
            // alteração de registro
            long codigo = cursor.getCodigo();
            String nome = jTextFieldNome.getText();
            String descricao = jTextFieldDescricao.getText();
            Modalidade modalidade = new Modalidade(codigo, nome, descricao);
            modalidadeDAO.alterar(modalidade);
        }
        ajustarExibicaoEstado(Estado.Navegando);
        // atualizar exibição de tabela no jFrameTabelaModalidade
        JFrameTabelaModalidade.getInstance().atualizarExibicaoTabela();
    }//GEN-LAST:event_jButtonSalvarActionPerformed

    private void jButtonExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExcluirActionPerformed
        if (JOptionPane.showConfirmDialog(null, 
                "Confirmar exclusão da modalidade selecionada?",
                "Exclusão", JOptionPane.YES_NO_OPTION)
                == JOptionPane.YES_OPTION) {
            int pos = listaModalidade.indexOf(cursor);
            modalidadeDAO.excluir(cursor);
            if (pos <= listaModalidade.size() - 1) {
                cursor = listaModalidade.get(pos);
            } else if (pos > 0) {
                cursor = listaModalidade.get(pos - 1);
            } else {
                cursor = null;
            }
            exibirDadosCursor();
            // atualizar exibição de tabela no jFrameTabelaModalidade
            JFrameTabelaModalidade.getInstance().atualizarExibicaoTabela();
        }
    }//GEN-LAST:event_jButtonExcluirActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAnterior;
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonEditar;
    private javax.swing.JButton jButtonExcluir;
    private javax.swing.JButton jButtonNovo;
    private javax.swing.JButton jButtonPrimeiro;
    private javax.swing.JButton jButtonProximo;
    private javax.swing.JButton jButtonSalvar;
    private javax.swing.JButton jButtonUltimo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField jTextFieldCodigo;
    private javax.swing.JTextField jTextFieldDescricao;
    private javax.swing.JTextField jTextFieldNome;
    // End of variables declaration//GEN-END:variables
}
